// src/lib/arena-picks.ts
// Loads MTGA draft pick statistics from /data/arena-picks-{set}.json
// Generated by tools/parse-arena-log.ts
//
// Pick rate → score conversion:
//   pick_rate 0.0 → score 1.0  (never picked, really bad)
//   pick_rate 0.5 → score 5.5  (middle of the pack)
//   pick_rate 1.0 → score 10.0 (always first-picked)

interface CardPickStats {
  picks: number;
  seen: number;
  pick_rate: number;
}

type PickMap = Record<string, CardPickStats>;

const _data: Record<string, PickMap> = {};
const _loaded = new Set<string>();
let _preloadPromise: Promise<void> | null = null;

async function _loadSet(setCode: string): Promise<void> {
  const key = setCode.toLowerCase();
  if (_loaded.has(key)) return;
  _loaded.add(key);
  try {
    const res = await fetch(`/data/arena-picks-${key}.json`);
    if (!res.ok) return;
    const data: PickMap = await res.json();
    _data[key] = data;
    console.log(`[ArenaPicks] Loaded ${Object.keys(data).length} cards for ${setCode.toUpperCase()}`);
  } catch {
    // File not present — silently skip
  }
}

export async function preloadArenaPicks(): Promise<void> {
  if (_preloadPromise) return _preloadPromise;
  _preloadPromise = Promise.all(['tdm', 'ltr'].map(_loadSet)).then(() => {});
  return _preloadPromise;
}

function _getStats(cardName: string): CardPickStats | null {
  const name = cardName.toLowerCase();
  for (const map of Object.values(_data)) {
    for (const [k, v] of Object.entries(map)) {
      if (k.toLowerCase() === name) return v;
    }
  }
  return null;
}

/**
 * Returns an Arena-pick-based score (0-10) or null if no data / too few samples.
 * Minimum 5 sightings required for trust.
 */
export function getArenaPickScore(cardName: string): number | null {
  const stats = _getStats(cardName);
  if (!stats || stats.seen < 5) return null;
  // Linear map: pick_rate [0, 1] → score [1.0, 10.0]
  return 1.0 + stats.pick_rate * 9.0;
}

/**
 * Trust factor [0, 1] based on how many times the card was seen.
 * Scales from 0 at 5 sightings to 1.0 at 50+ sightings.
 */
export function getArenaPickTrust(cardName: string): number {
  const stats = _getStats(cardName);
  if (!stats || stats.seen < 5) return 0;
  return Math.min(1.0, (stats.seen - 5) / 45);
}

/**
 * Returns true if any arena pick data has been loaded.
 */
export function hasArenaPickData(): boolean {
  return Object.keys(_data).length > 0;
}

/**
 * Stats summary for UI display.
 */
export function getArenaPickStats(): { sets: string[]; totalCards: number } {
  const sets = Object.keys(_data);
  const totalCards = sets.reduce((sum, s) => sum + Object.keys(_data[s]).length, 0);
  return { sets, totalCards };
}

// Preload on module import (non-blocking)
preloadArenaPicks().catch(() => {});
