// @ts-nocheck
// stack.ts — Re-exports from stack-part1.ts and stack-part2.ts

export {
  create,
  push,
  resolve,
  resolveEffects,
  _resolveItem,
  _payWardCost,
  _aiChooseModes,
} from './stack-part1';

export {
  handleBuffAll,
  handleBlight,
  handleBlightOpponent,
  handleGrantHaste,
  handleGrantHarmonize,
  handleStun,
  handleStunCounterSelf,
  handleThreaten,
  handleClash,
  handleCounterSpell,
  handleEndure,
  handleLoseLife,
  handleGainLife,
  handleDrain,
  handleLoot,
  handleRummage,
  handleBounceSelf,
  handleLookTop,
  handleDamageAll,
  handleUntapAll,
  handleDiscardHand,
  handleRevealHand,
  handleExileGraveyard,
  handleExileFromGraveyard,
  handleExileTop,
  handleDoubleCounters,
  handleBounceToLibraryTop,
  handleReturnLandFromMill,
  handleRegenerate,
  handleCounterSelfIfNoDraw,
  handleRemoveCounters,
  handleRemoveCountersAll,
  handleGrant,
  handleRegisterTempTrigger,
  handleGrantAll,
  handleGrantCounters,
  handleExileTopPlay,
  handleSearchLibrary,
  handleSearchLibraryToGraveyard,
  handleCreateTokenCopy,
  handleBecomeCopy,
  handleMassClone,
  handleGainControl,
  handleAnthem,
  handleTriggered,
  handleStatic,
  handleMoveCounters,
  handleDistributeCounters,
  handleBecomeCreature,
  handleAttach,
  handleExileTopOpponent,
  handleCopySpell,
  handleExtraCombat,
  handleExileGraveyardCastCopy,
  handleRingTempts,
  isEmpty,
  processNextEffect,
  payWardCost,
  aiScoreMode,
  aiChooseModes,
  aiChooseMode,
} from './stack-part2';
